# Generated by Django 5.0.6 on 2024-05-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('thumbnail_url', models.URLField()),
            ],
            options={
                'indexes': [models.Index(fields=['published_at'], name='videos_vide_publish_dd5f2e_idx')],
            },
        ),
    ]
