version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A youtube_fetcher worker --loglevel=info
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A youtube_fetcher beat --loglevel=info
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
